name: StartFollowing
description: Follow {{ player.name }} when asked. Use your best judgement on whether or not following through would make sense.
questEditorId: SeverActions
scriptName: SeverActions_Follow
executionFunctionName: StartFollowing
parameterMapping:
  - type: speaker
    name: akActor
    description: Speaker Actor parameter (triggering entity)
enabled: true